---
title: "Strings"
author: "Colin Pawlowski"
date: "October 26, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction
In this document, we go over strings in R.  This will be useful
for natural language processing that we will see later on.  

```{r Strings}
# Strings behave a little bit differently in R
# compared to other languages.  To get substrings,
# we use the substring() command.  We can also
# modify sections of the string.
x <- "abcdefg"
print(substring(x, 3, 5))
substr(x, 1, 2) <- "10"
print(x)
```

```{r String concatenation}
# We can concatenate strings in R using the paste() function.
# We can also specify the separator.
x <- "abc"
y <- "def"
z <- c("a", "b", "c")
paste(x, y)
paste0(x, y)
paste(x, y, sep = "_")
```

```{r Vectorized string concatenation}
# We can also concatenate vectors of strings
# or collapse them into 1 string.
z <- c("a", "b", "c")
paste0(z, "1")
paste(z, collapse = "-")
```

```{r String splitting}
# To split strings, we use the strsplit() function.
# The output is a list, so we extract the first element
# using [[1]].
strsplit("a|b|c|d", split = "|")
strsplit("a|b|c|d", split = "|")[[1]]
```

## String Matching
```{r Pattern matching}
# To find the elements of string vector that contain a certain
# pattern, we use the function grepl(<pattern>, <string vector>).
# For example, let's say that we want to find all of the strings
# in a vector that contain "a".  This function returns a vector of TRUE / FALSE
# corresponding to the elements which include the pattern.
# We can then use these as indices to see which strings in x
# matched this pattern.
x <- c("apple", "banana", "pop", "antarctica")
grepl("an", x)
x[grepl("an", x)]
```

```{r Regular Expressions}
# To match more general patterns, we use "regular expressions".
# For example, to find the elements of x which start with "a",
# we can use the "^a" regular expression:
x[grepl("^a", x)]
# To find the elements that end with "a",
# we use the "a$" regular expression:
x[grepl("a$", x)]
```

Functions using regular expressions are fast because the
operations are vectorized. For a detailed cheatsheet of
patterns that you can match using regular expressions in R, see
<https://www.rstudio.com/wp-content/uploads/2016/09/RegExCheatsheet.pdf>.

```{r Substituting Patterns}
# We can use regular expressions to perform string substitutions
# using the function gsub(<pattern>, <replacement>, <string vector>):
x <- c("big apple", "big banana", "small continent", "small lake")
gsub("big", "gigantic", x)
```

## Exercise
```{r Exercise}
# Read in the Airbnb reviews from the following file.
# Print out the first five reviews with include the phrase "bed bugs".
library(data.table)
reviews <- fread("data/reviews.csv", sep = ",")
```
